### ISSUE TITLE
Where is the mining.submit method?

### ISSUE THREAD

**Issue by laredotornado** [arnabk/stratum-client#2]
Hi,

I've been running the tests using a slushpool worker I set up but one thing I'm not understanding is where in your code do you provide an implementation for the submission of work completed?  That is, I dont' see anything that ipmlements the "mining.submit" method -- https://en.bitcoin.it/wiki/Stratum_mining_protocol#mining.submit , but maybe I'm missing something about what you have here.

Thanks for any info, - Dave

**Comment by arnabk** [comment]
`submit` has not been implemented. Open for PR.

**Comment by arnabk** [comment]
https://github.com/arnabk/stratum-client/pull/5

**Comment by arnabk** [comment]
https://github.com/arnabk/stratum-client/issues/2

**Comment by AnanthVivekanand** [comment]
PR has been submitted: 
https://github.com/arnabk/stratum-client/pull/5
